Repository Team-Smeme/Smeme-android, pull requests merged in 2023-01, with the labels that each got.

#16 hilt di name 미세팅된 부분 추가
  app/src/main/AndroidManifest.xml
Labels: FIX

#17 [#14] 임시 로티 스플레시 구성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/smeme/business/viewmodel/SplashViewModel.kt
  app/src/main/java/com/sopt/smeme/presentation/view/splash/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/raw/temp_lottie.json
Labels: 기능 추가

#37 인터셉터 세팅
  app/src/main/java/com/sopt/smeme/bridge/agent/AgentModule.kt
  app/src/main/java/com/sopt/smeme/bridge/agent/InjectWay.kt
  app/src/main/java/com/sopt/smeme/bridge/agent/user/MockProfileEditAgent.kt
  app/src/main/java/com/sopt/smeme/bridge/agent/user/MockSignInAgent.kt
  app/src/main/java/com/sopt/smeme/bridge/agent/user/ProfileAgent.kt
  app/src/main/java/com/sopt/smeme/bridge/agent/user/ProfileEditAgent.kt
  app/src/main/java/com/sopt/smeme/bridge/agent/user/SignInAgent.kt
  app/src/main/java/com/sopt/smeme/bridge/agent/user/SocialSignInAgent.kt
  app/src/main/java/com/sopt/smeme/bridge/controller/ApiConnectionModule.kt
  app/src/main/java/com/sopt/smeme/bridge/controller/AuthConnection.kt
  app/src/main/java/com/sopt/smeme/bridge/controller/ProfileConnection.kt
  app/src/main/java/com/sopt/smeme/bridge/controller/request/AuthenticateRequest.kt
  app/src/main/java/com/sopt/smeme/bridge/controller/request/Profile.kt
  app/src/main/java/com/sopt/smeme/bridge/controller/response/ServiceAccessData.kt
  app/src/main/java/com/sopt/smeme/business/policy/ProfilePolicy.kt
  app/src/main/java/com/sopt/smeme/business/viewmodel/ProfileInitializer.kt
  app/src/main/java/com/sopt/smeme/business/viewmodel/Receptionist.kt
  app/src/main/java/com/sopt/smeme/business/viewmodel/SplashViewModel.kt
  app/src/main/java/com/sopt/smeme/presentation/view/welcome/LoginProfileActivity.kt
  app/src/main/java/com/sopt/smeme/presentation/view/welcome/OnBoardingActivity.kt
  app/src/main/java/com/sopt/smeme/presentation/view/welcome/SplashActivity.kt
  app/src/main/java/com/sopt/smeme/system/network/ConnectCluster.kt
  app/src/main/java/com/sopt/smeme/system/network/NetworkModule.kt
  app/src/main/java/com/sopt/smeme/system/network/RequestInterceptor.kt
  app/src/main/java/com/sopt/smeme/system/storage/LocalDataStoreStorage.kt
  app/src/main/java/com/sopt/smeme/system/storage/LocalSharedPreference.kt
  app/src/main/java/com/sopt/smeme/system/storage/LocalStorage.kt
  app/src/main/java/com/sopt/smeme/system/storage/VolatileStorage.kt
Labels: 기능 개선

#32 [#31] 텍스트 스타일 추가
  app/src/main/res/values/styles.xml
Labels: 기능 추가
